version: '3.4'

services:
  backup:
    image: userid0x0/repo-backup:latest
    restart: unless-stopped
    # environment:
    #   RCLONE_REMOTE_NAME: 'RepoBackup'
    #   RCLONE_REMOTE_DIR: '/RepoBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
    #   SVN_REPO_NAME_0: 'repo-name'
    #   SVN_REPO_URL_0: 'http://your-server.internal/svn'
    #   SVN_REPO_USERNAME_0: 'backup'
    #   SVN_REPO_PASSWORD_0: '<secret>'
    #   CRON: '5 * * * *'
    #   ZIP_ENABLE: 'TRUE'
    #   ZIP_PASSWORD: 'WHEREISMYPASSWORD?'
    #   ZIP_TYPE: 'zip'
    #   BACKUP_FILE_SUFFIX: '%Y%m%d'
    #   BACKUP_KEEP_DAYS: 0
    #   PING_URL: ''
    #   MAIL_SMTP_ENABLE: 'FALSE'
    #   MAIL_SMTP_VARIABLES: ''
    #   MAIL_TO: ''
    #   MAIL_WHEN_SUCCESS: 'TRUE'
    #   MAIL_WHEN_FAILURE: 'TRUE'
    #   TIMEZONE: 'UTC'
    volumes:
      - rclone-data:/config/
    #   - /path/to/env:/.env

volumes:
  rclone-data:
    external: true

